### ISSUE TITLE
Scrolling inside the game

### ISSUE THREAD

**Issue by Yoh1612** [GoldenChrysus/ffxiv-ember-overlay#11]
Hi so i'm not sure why or if i done something wrong but everything works fine it just doesn't scroll while inside the game. It only work while i'm outside the game.

**Comment by GoldenChrysus** [comment]
Hello,

Do you have one of the "no focus" or "click through" options enabled in your plugin?

Also feel free to join our Discord so I can help you more quickly and we can go over troubleshooting steps: https://discord.io/emberoverlay

**Comment by GoldenChrysus** [comment]
Closing due to no update for several months.
