### ISSUE TITLE
Add settings "auto hide"

### ISSUE THREAD

**Issue by LuiceCreek** [GoldenChrysus/ffxiv-ember-overlay#12]
hide automatically inactive after x seconds

**Comment by GoldenChrysus** [comment]
Merged to [master](https://github.com/GoldenChrysus/ffxiv-ember-overlay/tree/master) in commit c32199c953b966698a47d1262eeb1dee8870adba. Released in version [0.14.0-alpha](https://github.com/GoldenChrysus/ffxiv-ember-overlay/tree/0.14.0-alpha). Closing.
