### ISSUE TITLE
Replace DPS TANK HEAL 24 With 'Back' Under Import

### ISSUE THREAD

**Issue by MrArca9** [GoldenChrysus/ffxiv-ember-overlay#18]
![image](https://user-images.githubusercontent.com/21209461/74108995-80947780-4b4d-11ea-88ed-abcdc0ff6890.png)
Example under focused view for player

![image](https://user-images.githubusercontent.com/21209461/74109002-8f7b2a00-4b4d-11ea-88fd-65992d5a98e0.png)
Under Import

**Comment by GoldenChrysus** [comment]
This is correct functionality. Going to import takes you out of the player view context. The state would have to be reworked to remember that you were viewing a player prior to import and which player. The development time is disproportionate to the benefit provided given that most users should be navigating to import very infrequently.

**Comment by MrArca9** [comment]
Further Explanation:

Going from all player view state to import view state should have a back button. Just like going from all player view state to individual player view state has a back button. Not Going from player view to import view. 

Back under import view could always return player to All player view?
