### ISSUE TITLE
Should Block % instead be Parry %?

### ISSUE THREAD

**Issue by falsefingolfin** [GoldenChrysus/ffxiv-ember-overlay#21]
I just assumed block % was meant to be parry %, but I've been using this overlay for several months and block % has never changed from 0%. I don't see a parry % option in the settings, is there any way you could add that stat to the overlay?

**Comment by GoldenChrysus** [comment]
Added in commit 7c9820218972de7485d84966082d52503927fa88. Released in [0.19.0-alpha](https://github.com/GoldenChrysus/ffxiv-ember-overlay/releases/tag/0.19.0-alpha).
