### ISSUE TITLE
Add Cactbot support please！

### ISSUE THREAD

**Issue by ShadyWhite** [GoldenChrysus/ffxiv-ember-overlay#3]
Add Cactbot support please！

**Comment by GoldenChrysus** [comment]
Hello,

Can you please describe in further detail what features you would expect to see in an implementation that supports Cactbot?

Thanks.

**Comment by ShadyWhite** [comment]
> Hello,
> 
> Can you please describe in further detail what features you would expect to see in an implementation that supports Cactbot?
> 
> Thanks.

Per-phase dps tracking or something more?

**Comment by GoldenChrysus** [comment]
Thanks; I will research this further this weekend.

**Comment by ShadyWhite** [comment]
> Thanks; I will research this further this weekend.

Cool!Thx!
