### ISSUE TITLE
Minimize to icon after combat

### ISSUE THREAD

**Issue by wdhwg001** [GoldenChrysus/ffxiv-ember-overlay#33]
Hi,

Thanks for creating such an amazing overlay!

I really like the feature of minimizing to a small icon, but I noticed that I need to manually minimize it after the fight.

Could you add a feature that the overlay can minimize to icon after combat? It would be even better if we can select which corner to automatically minimize to.

Thanks!

**Comment by GoldenChrysus** [comment]
There is already a setting to hide the overlay when inactive. Minimization would be redundant.

**Comment by wdhwg001** [comment]
Thanks for the reply! But I think minimizing is more frequently used as I still need to review the statistics. For the redundency I would suggest that we could have:
After Inactivity:
[Dropdown: Don't hide, Fold, Minimize to top left, Minimize to bottom left, ..., Hide completely]
Delay In Seconds:
[Draggable bar]

**Comment by wdhwg001** [comment]
It seems that this option isn't very hard to implement. If you don't have time to do it, will you accept a pr? I've noticed that the toggle uses jQuery, so I'll try to call its `togglePlaceholders` in `processAutoHide`.
