### ISSUE TITLE
Error when loading or reloading the overlay

### ISSUE THREAD

**Issue by fbl07** [GoldenChrysus/ffxiv-ember-overlay#38]
Since some time now (I think shortly after 5.5's release), the overlay just does not appear and when reloading the overlay in the plugin settings of ACT, it throws an error in the console. Rarely, the overlay actually works, but most of the time it does that. Restarting the game or ACT usually doesn't fix the issue. I know the error message doesn't say much information, let me know if there is something I can do to provide a better error message :  

`Info: Ember Spell Timer: BrowserConsole: Uncaught (in promise) undefined (Source: https://goldenchrysus.github.io/ffxiv/ember-overlay/#/, Line: 0)`

The same error happens with the parse version of the overlay as well, with the URL being the only difference. Let me know if there's anything you want me to test or if you have any questions regarding my setup that could help fix this.

**Comment by GoldenChrysus** [comment]
Need your full settings: ACT > Plugins > OverlayPlugin.dll > select overlay > Open DevTools > Application > IndexedDB > localforage > keyvaluepairs > copy entirety of value for `migration_history` and `settings_cache`. If the `settings_cache` value has any sensitive information in it, such as a webhook URL, please replace that with "redacted" so I know something has been removed.

**Comment by fbl07** [comment]
### Migration History : 
```

"["01-convert-binary-short-name-setting","02-store-settings-in-overlayplugin","03-convert-light-theme","04-convert-spell-layout","05-copy-spell-tts"]"
--


```

### Settings Cache

```
{"intrinsic":{"table_type":"dps","collapsed":false,"current_version":"0.28.0-alpha","last_version":"0.27.2-alpha","player_blur":false},"interface":{"player_name":"YOU","opacity":100,"zoom":100,"top_right_rank":false,"blur_job_icons":false,"collapse_down":true,"theme":"ffxiv-dark","minimal_theme":false,"footer_when_collapsed":true,"footer_dps":false,"hide_top_bar":true,"decimal_accuracy":2,"shorten_thousands":false,"language":"en","auto_hide":true,"auto_hide_delay":45},"custom":{"css":"","metric_names":{}},"tts":{"language":"en","rules":{"critical":{"tank":0,"heal":0,"dps":0,"all":0},"top":{"dps":false,"hps":false,"tps":false},"aggro":false,"encounter":{"start":false,"end":false}}},"table_settings":{"general":{"table":{"short_names":"no_short","footer_at_top":true,"percent_bars":true,"prioritize_party":false},"raid":{"short_names":"no_short","percent_bars":true,"prioritize_party":false}},"dps":{"show_footer":true},"heal":{"show_footer":true},"tank":{"show_footer":true}},"table_columns":{"dps":["damage%","encdps","crithit%","DirectHitPct","CritDirectHitPct","deaths"],"heal":["healed%","effective_heal_pct","enchps","effective_hps","OverHealPct","critheal%"],"tank":["damage_taken_pct","enctps","damagetaken","healstaken","BlockPct","ParryPct","deaths"],"raid":{"dps":["encdps","enchps"],"heal":["enchps","encdps"],"tank":["encdps","enchps"]}},"sort_columns":{"dps":"damage","heal":"healed","tank":"damagetaken","raid":"damage"},"detail_data":{"dps":["damage%","encdps","damage","crithit%","DirectHitPct","CritDirectHitPct","max_hit_format"],"heal":["healed%","effective_heal_pct","enchps","effective_hps","healed","OverHealPct","critheal%","max_heal_format"],"tank":["damage_taken_pct","damagetaken","enctps","healstaken","BlockPct","deaths"]},"discord":{"url":""},"spells_mode":{"spells":["7436","166","16483","16552","7448","7518","7520","7521","7517","7519","16146","16138","16164","136","3571","7383","23","29","16482","20","16508","16803","3581","3590"],"effects":["1834","71","74"],"dots":["1895","1228","1871","725","1215","1881"],"party_spells":["2258","3557","7396","118","15998","7520","16552","7436"],"party_effects":["786","1185","141","1822","1239","1878"],"party_dots":[],"reverse_skill":false,"reverse_effect":false,"reverse_dot":false,"party_reverse_skill":false,"party_reverse_effect":false,"party_reverse_dot":false,"always_skill":true,"always_effect":false,"always_dot":true,"warning_threshold":6,"spells_per_row":5,"show_icon":true,"use_tts":false,"party_use_tts":false,"party_zones":[],"tts_trigger":"zero","minimal_layout":false,"invert_vertical":false,"invert_horizontal":false,"designer":{"skill":{"warning":true,"indicator":"ticking","cooldown_bottom_left":false},"effect":{"border":false,"warning":true,"indicator":"ticking","cooldown_bottom_left":false},"dot":{"border":true,"warning":true,"indicator":"ticking","cooldown_bottom_left":false},"general":{"show_hover_names":false}},"ui":{"use":true,"sections":{"27ee7f0f-e64e-4c58-87d6-43f59d738b21":{"types":["you-effect","you-dot","you-skill"],"layout":{"x":0,"y":0,"width":300,"height":300,"layout":"normal","spells_per_row":5}}}},"layout":"normal","always_skill_static":false}}
```

Let me know if you need anything else.

**Comment by GoldenChrysus** [comment]
Let me know if the same error occurs on https://goldenchrysus.github.io/ffxiv/ember-overlay-dev/

**Comment by fbl07** [comment]
Yes, it does also happen with that URL. Either if I restart ACT or if I hit "Reload Overlay", it gives the same error.

**Comment by GoldenChrysus** [comment]
On that URL, you should now receive several numbers in the console. Please send a screenshot of the full console (Open DevTools, not the OP log). Only on a reload where the error occurs. If you don't get any numbers, you may need to keep reloading until your browser decides to pull the latest code.

**Comment by fbl07** [comment]
![Capture](https://user-images.githubusercontent.com/9098771/116838054-f34aa200-ab9a-11eb-9d25-9cb2c75b4df9.PNG)

Ah the good ol' put prints and see how many of them come out so you can spot the error lol

**Comment by GoldenChrysus** [comment]
Please try again. You will know that you're on the latest code because the first message will be "rev1." So refresh until you see that.

**Comment by fbl07** [comment]
![Capture](https://user-images.githubusercontent.com/9098771/116838848-ed09f500-ab9d-11eb-8bbe-d3d8308df066.PNG)
Still gets to 11

**Comment by GoldenChrysus** [comment]
Updated. rev2. It is failing at saving your settings, so it should give an error this time. I think the only time I've seen localforage fail at saving someone's settings was when their disk was nearly full or if the browser's limits had been reached...

**Comment by fbl07** [comment]
My computer had been telling me I was running out of space for a bit now, clearing up space did seem to fix the issue indeed. I'll get back to you on #38 in a bit when I'm not mid trial

**Comment by GoldenChrysus** [comment]
Make sure for #37 that you recheck your setup, since your settings haven't been saving. e.g. the settings you sent here don't have a UI section for party timers.
