### ISSUE TITLE
Settings button do not show.

### ISSUE THREAD

**Issue by ShadyWhite** [GoldenChrysus/ffxiv-ember-overlay#4]
Settings button do not show.

**Comment by GoldenChrysus** [comment]
Settings button is a staging-only release and is not yet a production feature. The default branch is bleeding-edge in the repo; view master for production information. Alternatively, version-specific information is provided in the Discord at https://discord.io/emberoverlay. 

To use/test the settings feature, change your overlay URL from https://goldenchrysus.github.io/ffxiv/ember-overlay/ to https://goldenchrysus.github.io/ffxiv/ember-overlay-dev/
