### ISSUE TITLE
A few requests if possible for Spell Timers

### ISSUE THREAD

**Issue by rushtothesun** [GoldenChrysus/ffxiv-ember-overlay#40]
**Describe the feature you'd like**
-Option to disable truncated names or change the name width
-Option to change the "ticking" fill in color
-Option to have separate TTS triggers for the sections Spells & Buffs/Effects

**Is your feature request related to a problem? Please describe.**
No

**Additional context**

Example:
![image](https://user-images.githubusercontent.com/20650932/120245145-e66cad00-c231-11eb-9046-d6d190538007.png)

There is enough space for Standard Step to be spelled out fully but it gets truncated. Also in the picture, the transparent black ticking color on top of the dark grey background makes it very hard to see. A color picker would be nice to change the color or at least an option for a lighter color. 

For the TTS triggers currently with that option it TTS's everything when I just want my Spell CDs to have TTS when they're about to come up. A TTS option under Spells for only Spells and a TTS option under Buffs/Effects for only Buffs/Effects would be great.

**Comment by GoldenChrysus** [comment]
1. Maybe when CSS container queries are supported, as the truncation is currently  a limitation of requiring that the name fits for every possible timer size and duration. Don't want to implement it with JS as timers are already resource heavy.
2. Ember doesn't provide color customization nor does it plan to. Use CSS.
3. Already a planned feature for UI builder sections.
