### ISSUE TITLE
Allow No More Than One Settings Window

### ISSUE THREAD

**Issue by tylercrompton** [GoldenChrysus/ffxiv-ember-overlay#42]
**Describe the bug**
Currently, the user can open multiple settings windows.

**Reproduction steps**
Exact steps, both in Ember and within FFXIV, to reproduce the behavior:
1. Open the settings.
2. Without closing the settings window, open the settings again.

**Expected behavior**
If a settings window is already open, then another one shouldn't be opened. Ideally, focus should be moved to the already opened window.

**Screenshots**
![image](https://user-images.githubusercontent.com/997507/120695403-f8885e80-c470-11eb-9dac-3669ad16314d.png)

**Settings data**
Paste your settings data below. This can be found at ACT > Plugins > OverlayPlugin.dll > (select overlay) > Open DevTools > Application > IndexedDB > localforage > keyvaluepairs > (copy the entire value for `settings_cache`). Replace any sensitive information (such as a webhook URL) with the word "redacted".

Not applicable

**Comment by GoldenChrysus** [comment]
Not possible.

**Comment by tylercrompton** [comment]
That was a ridiculously hasty close of an issue. Do you mind elaborating?

Providing a `windowName` argument to `window.open` doesn't work? https://github.com/GoldenChrysus/ffxiv-ember-overlay/blob/37ceb5a7f2f030c21f218b316ff850e77f99a0ce/src/services/SettingsService.js#L18

Is it not possible to track the window via the return value of `window.open`? For example, consider the following (simplified) pseudocode:

```js
if (settingsWindow) {
    settingsWindow.focus();
} else {
    settingsWindow = window.open(`${querystring}#/settings/about`, "", "width=1000,height=630,location=no,menubar=no");
    settingsWindow.addEventListener('unload', () => {
        settingsWindow = null;
    });
}
```

It's been a while since I've worked with react-redux, so I don't remember the proper way of doing this, but you get the idea.

If neither of those potential solutions are viable, then have you considered replacing the contents of the `#inner` element with the `Settings` component? (I realize that this sounds simpler than it is.)

I feel that several possible solutions could be considered, but your comment doesn't explain what solutions that you might already attempted during the initial implementation of the settings feature.

**Comment by GoldenChrysus** [comment]
Putting the settings into the overlay would never be implemented. Most users run their overlays in very small dimensions, so accessing the settings and being able to actually read/use them would require them to resize their overlays every single time. That's an overengineered solution and creates a poor user experience for tens of thousands of users to "resolve" what is ultimately a problem of one person's user error.
