### ISSUE TITLE
Porn Ads

### ISSUE THREAD

**Issue by gucciBane** [GoldenChrysus/ffxiv-ember-overlay#43]
Hey. I clicked the 'Support Ember' ad button and got 3 windows of porn popups.

**Comment by ellielle** [comment]
When I clicked it, it took me to one of those sketchy-ass ad spam sites that make you thank the twelve you have NoScript.

**Comment by moonlitglare** [comment]
I'm happy to watch an unobtrusive ad, but I'm not willing to allow any of this potential malware on my system. Also, yeah, it's serving penis pump, male enhancement, and porn ads. This isn't a good idea. Just let people donate to a PayPal or a Ko-Fi if they want to support this. Now your overlay is a potential security risk.

**Comment by rozinky** [comment]
Echoing these concerns as well. Whatever ad network you are signed up with is serving sleezy garbage and malware. You need to find a reputable ad network if this is how you want to try and support your development.
