### ISSUE TITLE
Let Auto-Hide collapse to corner instead of making the overlay invisible

### ISSUE THREAD

**Issue by kwaschny** [GoldenChrysus/ffxiv-ember-overlay#48]
**Describe the feature you'd like**
Right now, using Auto-Hide will hide the overlay completely, making it difficult to restore the overlay manually. Offering an option to let Auto-Hide collapse to one of the 4 corners instead, will improve the feature by allowing another use case.

**Is your feature request related to a problem? Please describe.**
I would like to use the Auto-Hide feature without losing the ability to make the overlay visible before entering combat.

**Describe alternatives you've considered**
Manually collapse/expand the overlay whenever I want to see it.

**Comment by GoldenChrysus** [comment]
Released in version 1.9.0.
