### ISSUE TITLE
Spell timers 'latest changes' overlay while on different unconfigured jobs 

### ISSUE THREAD

**Issue by syd-h** [GoldenChrysus/ffxiv-ember-overlay#49]
**Describe the bug**
Spell timer is setup for GBN only and anytime I'm on another job I get this overlay that is 100% in the way and unable to be dismissed with out first swapping to GBN then back to another job. This only happens if I start ACT while not on GBN.

**Reproduction steps**
1. Set up Spell Timers for GBN and have the overlay in a lower section of your display
2. Don't setup Spell Timers for any other job
3. Get 'latest changes' covering the area where you previously had put your Spell Timer window when starting ACT **while not on GBN**.

**Expected behavior**
No overlay or anything when on a different job that has not been configured with Spell Timers. If I need to see latest changes then come here or go to the 'About' section in the settings panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/25559485/152468253-8b778317-6a62-44de-8c75-f0c4ab6b1e5f.png)

**Settings data**

"{\"intrinsic\":{\"table_type\":\"dps\",\"collapsed\":false,\"current_version\":\"1.0.0\",\"last_version\":\"0.0.0\",\"player_blur\":false},\"interface\":{\"player_name\":\"YOU\",\"opacity\":100,\"zoom\":100,\"text_scale\":100,\"top_right_rank\":false,\"blur_job_icons\":false,\"collapse_down\":false,\"theme\":\"ffxiv-dark\",\"minimal_theme\":false,\"horizontal\":false,\"horizontal_shrink\":false,\"horizontal_alignment\":\"left\",\"footer_when_collapsed\":false,\"footer_dps\":false,\"hide_top_bar\":true,\"decimal_accuracy\":2,\"shorten_thousands\":false,\"language\":\"en\",\"auto_hide\":false,\"auto_hide_delay\":0,\"display_job_names\":false},\"custom\":{\"css\":\"\",\"metric_names\":{}},\"tts\":{\"language\":\"en\",\"rules\":{\"critical_hp\":{\"tank\":0,\"heal\":0,\"dps\":0,\"all\":0},\"critical_mp\":{\"tank\":0,\"heal\":0,\"dps\":0,\"all\":0},\"top\":{\"dps\":false,\"hps\":false,\"tps\":false},\"aggro\":false,\"encounter\":{\"start\":false,\"end\":false}}},\"table_settings\":{\"general\":{\"table\":{\"short_names\":\"no_short\",\"footer_at_top\":false,\"percent_bars\":true,\"prioritize_party\":false},\"raid\":{\"short_names\":\"no_short\",\"percent_bars\":true,\"prioritize_party\":false}},\"dps\":{\"show_footer\":true},\"heal\":{\"show_footer\":true},\"tank\":{\"show_footer\":true}},\"table_columns\":{\"dps\":[\"damage%\",\"encdps\",\"crithit%\",\"DirectHitPct\",\"CritDirectHitPct\"],\"heal\":[\"healed%\",\"effective_heal_pct\",\"enchps\",\"effective_hps\",\"OverHealPct\",\"critheal%\"],\"tank\":[\"damage_taken_pct\",\"enctps\",\"damagetaken\",\"healstaken\",\"BlockPct\",\"ParryPct\",\"deaths\"],\"raid\":{\"dps\":[\"encdps\",\"enchps\"],\"heal\":[\"enchps\",\"encdps\"],\"tank\":[\"encdps\",\"enchps\"]}},\"sort_columns\":{\"dps\":\"damage\",\"heal\":\"healed\",\"tank\":\"damagetaken\",\"raid\":\"damage\"},\"detail_data\":{\"dps\":[\"damage%\",\"encdps\",\"damage\",\"crithit%\",\"DirectHitPct\",\"CritDirectHitPct\",\"max_hit_format\"],\"heal\":[\"healed%\",\"effective_heal_pct\",\"enchps\",\"effective_hps\",\"healed\",\"OverHealPct\",\"critheal%\",\"max_heal_format\"],\"tank\":[\"damage_taken_pct\",\"damagetaken\",\"enctps\",\"healstaken\",\"BlockPct\",\"deaths\"]},\"discord\":{\"url\":\"\"},\"spells_mode\":{\"spells\":[\"16138\",\"16146\",\"16165\",\"16164\"],\"effects\":[\"1831\"],\"dots\":[\"1837\",\"1838\"],\"debuffs\":[],\"party_spells\":[],\"party_effects\":[],\"party_dots\":[],\"party_debuffs\":[],\"reverse_skill\":false,\"reverse_effect\":false,\"reverse_dot\":false,\"reverse_debuff\":false,\"party_reverse_skill\":false,\"party_reverse_effect\":false,\"party_reverse_dot\":false,\"party_reverse_debuff\":false,\"always_skill\":true,\"always_effect\":true,\"always_dot\":false,\"always_debuff\":false,\"warning_threshold\":2,\"spells_per_row\":4,\"show_icon\":true,\"use_tts\":false,\"party_use_tts\":false,\"tts_on_effect\":false,\"party_tts_on_skill\":false,\"party_tts_on_effect\":false,\"party_zones\":[],\"tts_trigger\":\"zero\",\"minimal_layout\":false,\"invert_vertical\":false,\"invert_horizontal\":false,\"designer\":{\"skill\":{\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"effect\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"dot\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"debuff\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"general\":{\"show_hover_names\":false}},\"ui\":{\"use\":false,\"sections\":{}},\"layout\":\"icon\",\"always_skill_static\":true,\"always_effect_static\":true}}"

**Comment by GoldenChrysus** [comment]
Ember has no way of knowing that you only want to see the overlay when on GNB. It cannot be spell-based as countless items are not job-specific. Please close the overlay if you do not need to use it. This is configured within OverlayPlugin and OverlayPlugin provides functionality for hiding overlays with hotkeys. Alternatively, use the UI Builder if you want more control over Ember's UI.

**Comment by syd-h** [comment]
In that case why does the overlay only show up with the GBN added items when only on GBN? Is that not sort of what it is already doing in some way?

Eitherway UI Builder works so thanks still.

**Comment by GoldenChrysus** [comment]
It was stated that jobs cannot be used for your desired functionality. It was not stated that Ember does not use job data at all.
