### ISSUE TITLE
Black Mage incorrectly named

### ISSUE THREAD

**Issue by bnizzle** [GoldenChrysus/ffxiv-ember-overlay#50]
When using the setting "Use Job Names Instead of Player Names" Black Mage is incorrectly set to "Black Bage"

A change to the name in [src/constants/index.js](https://github.com/GoldenChrysus/ffxiv-ember-overlay/blob/ead66456f4096b2ff3af7986639bc28277e705de/src/constants/index.js) on line 215 will fix it up

**Comment by GoldenChrysus** [comment]
Already resolved.
