### ISSUE TITLE
Incorrect cooldowns after traits

### ISSUE THREAD

**Issue by JamesAndrewsXV** [GoldenChrysus/ffxiv-ember-overlay#56]
Edited to correct inaccuracies of level acquisition

**Describe the bug**

Hissatsu: Senei ad Hissatsu: Guren continue to display a 120s cooldown in the spell timers, despite the level 94 trait that reduces its cooldown to 60s. Furthermore, Manafont continues to display a cooldown of 120s despite the level 84 trait that reduces it to 100s. 

**Reproduction steps**
Exact steps, both in Ember and within FFXIV, to reproduce the behavior:
1. Add Manafont, Hissatsu: Guren and Hissatsu: Senei to Ember Spell Timers
2. Job change to Samurai at level 94 or above 
3. Build 25 kenki and cast 'Hissatsu:Senei' or 'Hissatsu: Guren' in game
4. Job change to Black Mage at level 84 for above
5. Use a fire spell and cast Manafont
**Expected behavior**

Recast times of Hissatsu: Senei and Manafont should match their level 100 recast. Alternatively, it matches recast only with the trait enabled.

**Screenshots**
If applicable, add screenshots to help explain the issue.

![image](https://github.com/user-attachments/assets/f9429b38-fe74-4504-be43-0feec10719db)

![image](https://github.com/user-attachments/assets/e4e47dfd-d290-45a3-8185-489487f9cab4)

**Settings data**
Paste your settings data below. This can be found at ACT > Plugins > OverlayPlugin.dll > (select overlay) > Open DevTools > Application > IndexedDB > localforage > keyvaluepairs > (copy the entire value for `settings_cache`). Replace any sensitive information (such as a webhook URL) with the word "redacted".

"{\"intrinsic\":{\"table_type\":\"dps\",\"collapsed\":false,\"current_version\":\"1.4.0\",\"last_version\":\"0.0.0\",\"player_blur\":false},\"interface\":{\"player_name\":\"YOU\",\"opacity\":100,\"zoom\":203,\"text_scale\":100,\"top_right_rank\":false,\"blur_job_icons\":false,\"collapse_down\":false,\"theme\":\"ffxiv-dark\",\"minimal_theme\":false,\"horizontal\":false,\"horizontal_shrink\":false,\"horizontal_alignment\":\"left\",\"footer_when_collapsed\":false,\"footer_dps\":false,\"hide_top_bar\":false,\"decimal_accuracy\":2,\"shorten_thousands\":false,\"language\":\"en\",\"auto_hide\":\"disabled\",\"auto_hide_delay\":0,\"display_job_names\":false},\"custom\":{\"css\":\"\",\"metric_names\":{}},\"tts\":{\"language\":\"en\",\"rules\":{\"critical_hp\":{\"tank\":0,\"heal\":0,\"dps\":0,\"all\":0},\"critical_mp\":{\"tank\":0,\"heal\":0,\"dps\":0,\"all\":0},\"top\":{\"dps\":false,\"hps\":false,\"tps\":false},\"aggro\":false,\"encounter\":{\"start\":false,\"end\":false}}},\"table_settings\":{\"general\":{\"table\":{\"short_names\":\"no_short\",\"footer_at_top\":false,\"percent_bars\":true,\"prioritize_party\":false},\"raid\":{\"short_names\":\"no_short\",\"percent_bars\":true,\"prioritize_party\":false}},\"dps\":{\"show_footer\":true},\"heal\":{\"show_footer\":true},\"tank\":{\"show_footer\":true}},\"table_columns\":{\"dps\":[\"damage%\",\"encdps\",\"crithit%\",\"DirectHitPct\",\"CritDirectHitPct\"],\"heal\":[\"healed%\",\"effective_heal_pct\",\"enchps\",\"effective_hps\",\"OverHealPct\",\"critheal%\"],\"tank\":[\"damage_taken_pct\",\"enctps\",\"damagetaken\",\"healstaken\",\"BlockPct\",\"ParryPct\",\"deaths\"],\"raid\":{\"dps\":[\"encdps\",\"enchps\"],\"heal\":[\"enchps\",\"encdps\"],\"tank\":[\"encdps\",\"enchps\"]}},\"sort_columns\":{\"dps\":\"damage\",\"heal\":\"healed\",\"tank\":\"damagetaken\",\"raid\":\"damage\"},\"detail_data\":{\"dps\":[\"damage%\",\"encdps\",\"damage\",\"crithit%\",\"DirectHitPct\",\"CritDirectHitPct\",\"max_hit_format\"],\"heal\":[\"healed%\",\"effective_heal_pct\",\"enchps\",\"effective_hps\",\"healed\",\"OverHealPct\",\"critheal%\",\"max_heal_format\"],\"tank\":[\"damage_taken_pct\",\"damagetaken\",\"enctps\",\"healstaken\",\"BlockPct\",\"deaths\"]},\"discord\":{\"url\":\"\",\"metrics\":[\"encdps\",\"enchps\"],\"sort\":\"damage\"},\"spells_mode\":{\"spells\":[\"3625\",\"7390\",\"29056\",\"29054\",\"25801\",\"2248\",\"16138\",\"29105\",\"7520\",\"3557\",\"16493\",\"2264\",\"20\",\"7383\",\"7395\",\"7396\",\"16552\",\"158\",\"24405\",\"29552\",\"29659\",\"34647\",\"36957\",\"16481\"],\"effects\":[\"3248\"],\"dots\":[],\"debuffs\":[],\"party_spells\":[],\"party_effects\":[],\"party_dots\":[],\"party_debuffs\":[],\"reverse_skill\":false,\"reverse_effect\":false,\"reverse_dot\":false,\"reverse_debuff\":false,\"party_reverse_skill\":false,\"party_reverse_effect\":false,\"party_reverse_dot\":false,\"party_reverse_debuff\":false,\"always_skill\":false,\"always_effect\":false,\"always_dot\":false,\"always_debuff\":false,\"warning_threshold\":2,\"spells_per_row\":2,\"show_icon\":true,\"use_tts\":false,\"party_use_tts\":false,\"tts_on_effect\":false,\"party_tts_on_skill\":false,\"party_tts_on_effect\":false,\"party_zones\":[],\"tts_trigger\":\"zero\",\"minimal_layout\":false,\"invert_vertical\":true,\"invert_horizontal\":true,\"designer\":{\"skill\":{\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"effect\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"dot\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"debuff\":{\"border\":false,\"warning\":true,\"indicator\":\"ticking\",\"cooldown_bottom_left\":false},\"general\":{\"show_hover_names\":false}},\"ui\":{\"use\":true,\"sections\":{\"652d144d-5147-45a6-874a-d5322aa9cbc3\":{\"types\":[\"you-skill\"],\"layout\":{\"x\":900,\"y\":500,\"width\":100,\"height\":100,\"layout\":\"default\",\"spells_per_row\":-1}},\"3282834d-27d0-4eda-be35-993885e20036\":{\"types\":[\"you-effect\"],\"layout\":{\"x\":660,\"y\":490,\"width\":100,\"height\":100,\"layout\":\"default\",\"spells_per_row\":-1}}}},\"layout\":\"icon\"}}"

**Comment by GoldenChrysus** [comment]
Resolved in version 1.9.4. Please check.

**Comment by JamesAndrewsXV** [comment]
Looks good! That was quick, thank you.
