### ISSUE TITLE
New class colors

### ISSUE THREAD

**Issue by Krolja** [GoldenChrysus/ffxiv-ember-overlay#58]
The backgrounds on the DPS meter for the two new classes are a different shade of red than what is implemented for the previous DPS classes. Would like a way to adjust them/fix them. Not a major issue. I would just enjoy the uniformity.

**Comment by GoldenChrysus** [comment]
Please follow the appropriate issue template and provide an example of what you are referring to.

**Comment by GoldenChrysus** [comment]
FYI, there are no role-based colors by default in Ember. I assume you are using custom CSS. If so, you would need to correct the CSS yourself or ask the author to do so. Closing this as you should follow the proper issue template and provide more information.
