### ISSUE TITLE
Add chinese translation please

### ISSUE THREAD

**Issue by ShadyWhite** [GoldenChrysus/ffxiv-ember-overlay#7]
I can give some translate help.

**Comment by GoldenChrysus** [comment]
In the next reddit update post in about 15 days, translation help is going to be requested, and that's when development of a translation system will begin (if I get decent help). I'll keep you updated.

**Comment by GoldenChrysus** [comment]
If still able to help with translation, please join the Discord (https://discord.io/emberoverlay) and sign up in #translation-signup.

**Comment by GoldenChrysus** [comment]
Added in version 0.10.0-alpha.
