### ISSUE TITLE
Custom CSS persists, but Custom CSS settings are sanitized when closing/re-opening settings

### ISSUE THREAD

**Issue by rogersjc42** [GoldenChrysus/ffxiv-ember-overlay#8]
When one adds Custom CSS, the changes are enabled (as long as one can find the correct id/classes). While the changes persist, the actual CSS does not as demonstrated here: https://gyazo.com/9743da9238e3c3fc970c3fad2d3ce0cc

To be clear, whatever Custom CSS is added stays in effect even after closing Settings, reloading the overlay, or closing/opening ACT. The issue is the field is sanitized when any of the above actions are taken. This can make Custom CSS difficult, as one would need to go look at the source code to find the correct ids/classes.

**Comment by GoldenChrysus** [comment]
Resolved in commit 0abee95. Updated changelog.
