### ISSUE TITLE
Full Screen Installation Steps

### ISSUE THREAD

**Issue by austinrr** [GoldenChrysus/ffxiv-ember-overlay#9]
It's mentioned in the readme that the overlay plugin might be used when running in fullscreen:

>  If you wish to remain in full screen mode, you must use OverlayPlugin.

Per this ticket, would it be possible to add the additional instructions for setting up the overlay to work while running in fullscreen (not borderless windowed)?

**Comment by GoldenChrysus** [comment]
I believe the information may be inaccurate at this point. There is apparently a recent Windows 10 update that broke OverlayPlugin's ability to overlay over the full-screen game. There are no additional steps to make OverlayPlugin work with full screen, so the README will be updated with this caveat.

**Comment by GoldenChrysus** [comment]
As overlays no longer operate in full screen mode, this is being closed.
